/// <reference types="react-scripts" />
declare module 'react-stockcharts'
declare module 'react-stockcharts/lib/series'
declare module 'react-stockcharts/lib/axes'
declare module 'react-stockcharts/lib/helper'
declare module 'react-stockcharts/lib/utils'
declare module 'react-stockcharts/lib/scale'
declare module 'react-stockcharts/lib/tooltip'
declare module 'd3-scale'
declare module 'd3-time'
